### PR TITLE
Fixes for running the packer in JS

### LINKED ISSUE #10: AstMemory invokes undefined behavior on alignment
I am porting the packer to JS for #9. While doing so I noticed that it does an unaligned write to a double. The issue is that `AstMemory` simply returns a pointer and bumps the current position in the arena. Many of the sizes it allocates are not multiples of 8, so `DoubleNode`, which stores a double, can get misaligned.

Am I missing something here?

I'll make it just allocate a number of bytes that is a multiple of 8 for now. A better option might be separate arenas, etc.

### PR DESCRIPTION
**Pull request by kripken**
Fixes #10 and other stuff noticed while getting the packer to run in the shell.

### CODE REVIEW

File: src/unpack.cpp [hunk 1]
```diff
@@ -2407,7 +2408,7 @@ asmjs::unpack(const uint8_t* packed, const char* cb_name, uint32_t unpacked_size
 
 #endif
 
-#ifdef EMSCRIPTEN
+#if defined(__EMSCRIPTEN__) && !defined(CHECKED_OUTPUT_SIZE)
```
Comment (kripken) [inline src/unpack.cpp]: In other words, being an emscripten build doesn't mean one is running the client-side unpacker, it could also be the server-side packer.

File: src/pack-asmjs.cpp [hunk 2]
```diff
@@ -152,6 +152,8 @@ class AstMemory
 
   void* alloc(size_t bytes)
   {
+    bytes = (bytes + 7)&-8; // some of our data structures, like DoubleNode, need 8-byte alignment
```
Comment (lukewagner) [inline src/pack-asmjs.cpp]: Can you add space before after '&' and '-'?

**Comment by lukewagner** [comment]
Looks good w/ that one nit.

File: src/pack-asmjs.cpp (hunk 2 above)
Comment (kripken) [inline src/pack-asmjs.cpp]: I assume just before and after `&`, and not after `-`? i pushed that now.

Comment (lukewagner) [inline src/pack-asmjs.cpp]: Oops, you're right :)
